import "./globals.css";
import Navbar from "./navbar";
import StoreProvider from "./store-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body      >
        <StoreProvider>
        <Navbar/>
        {children}
        </StoreProvider>
       
      </body>
    </html>
  );
}
